# Generated by Django 4.1.5 on 2023-01-16 12:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='옵션명')),
                ('price', models.PositiveBigIntegerField(default=0, verbose_name='옵션가격')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='재고')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='대표이름')),
                ('price', models.PositiveBigIntegerField(default=0, verbose_name='기본가격')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='수량')),
                ('shipping', models.BooleanField(default=False, verbose_name='배송비')),
                ('total_price', models.PositiveBigIntegerField(default=0, verbose_name='총가격')),
                ('is_cart', models.BooleanField(default=False, verbose_name='장바구니 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='주문일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='store.option')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='store.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='option',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='store.product'),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='수량')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='장바구니 담은 날짜')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='store.option')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='store.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
