# Generated by Django 4.1.5 on 2023-01-16 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='shipping',
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_price',
            field=models.PositiveBigIntegerField(default=3000, verbose_name='배송비'),
        ),
    ]
