# Generated by Django 4.1.5 on 2023-01-16 16:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0002_remove_order_shipping_order_shipping_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_cart',
        ),
        migrations.RemoveField(
            model_name='order',
            name='option',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_address',
            field=models.CharField(default='', max_length=255, verbose_name='배송지'),
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='수량')),
                ('total_price', models.PositiveBigIntegerField(default=0, verbose_name='옵션 총 가격')),
                ('is_cart', models.BooleanField(default=False, verbose_name='장바구니 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='구매일')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='store.option')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='store.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='store.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
