# Generated by Django 4.1.5 on 2023-01-16 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_order_is_cart_remove_order_option_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='shipping_price',
            new_name='shipping_fee',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='is_cart',
        ),
        migrations.AddField(
            model_name='order',
            name='is_cart',
            field=models.BooleanField(default=False, verbose_name='장바구니 여부'),
        ),
    ]
