# Generated by Django 4.1.5 on 2023-01-18 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_rename_shipping_price_order_shipping_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='shipping_fee',
            field=models.PositiveBigIntegerField(default=3000, verbose_name='배송비'),
        ),
    ]
